/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorsains;

/**
 *
 * @author WINDOWS 10
 */
public class Kal extends javax.swing.JFrame {
    String number = "";
    double nomor1, nomor2,jumlah;
    int pilih;
    public Kal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        invut = new javax.swing.JTextField();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        modulus = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        invut.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        invut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        invut.setText("0");
        invut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invutActionPerformed(evt);
            }
        });
        getContentPane().add(invut);
        invut.setBounds(30, 28, 390, 41);

        sin.setText("Sin");
        buttonGroup1.add(sin);
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });
        getContentPane().add(sin);
        sin.setBounds(30, 82, 90, 50);

        cos.setText("Cos");
        buttonGroup1.add(cos);
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });
        getContentPane().add(cos);
        cos.setBounds(30, 140, 90, 50);

        tan.setText("Tan");
        buttonGroup1.add(tan);
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });
        getContentPane().add(tan);
        tan.setBounds(30, 200, 90, 50);

        pangkat.setText("pangkat");
        pangkat.setBorderPainted(false);
        buttonGroup1.add(pangkat);
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        getContentPane().add(pangkat);
        pangkat.setBounds(310, 80, 110, 50);

        modulus.setText("Modulus");
        buttonGroup1.add(modulus);
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });
        getContentPane().add(modulus);
        modulus.setBounds(310, 140, 110, 50);

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        getContentPane().add(num1);
        num1.setBounds(150, 80, 40, 50);

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        getContentPane().add(num2);
        num2.setBounds(200, 80, 40, 50);

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        getContentPane().add(num3);
        num3.setBounds(250, 80, 40, 50);

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        getContentPane().add(num4);
        num4.setBounds(150, 140, 40, 50);

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        getContentPane().add(num5);
        num5.setBounds(200, 140, 40, 50);

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        getContentPane().add(num6);
        num6.setBounds(250, 140, 40, 50);

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        getContentPane().add(num7);
        num7.setBounds(150, 200, 40, 50);

        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        getContentPane().add(num0);
        num0.setBounds(200, 260, 40, 50);

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        getContentPane().add(num9);
        num9.setBounds(250, 200, 40, 50);

        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        getContentPane().add(samadengan);
        samadengan.setBounds(30, 260, 160, 50);

        hapus.setText("C");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(250, 260, 40, 50);

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        getContentPane().add(num8);
        num8.setBounds(200, 200, 40, 50);

        plus.setText("+");
        buttonGroup1.add(plus);
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus);
        plus.setBounds(310, 200, 50, 50);

        minus.setText("-");
        buttonGroup1.add(minus);
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus);
        minus.setBounds(370, 200, 50, 50);

        kali.setText("x");
        buttonGroup1.add(kali);
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(370, 260, 50, 50);

        bagi.setText("/");
        buttonGroup1.add(bagi);
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        getContentPane().add(bagi);
        bagi.setBounds(310, 260, 50, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invutActionPerformed

    }//GEN-LAST:event_invutActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("tan");
        pilih = 7;
    }//GEN-LAST:event_tanActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        number += "1";
        invut.setText(number);
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed

        number += "2";
        invut.setText(number);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        number += "3";
        invut.setText(number);
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        number += "4";
        invut.setText(number);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        number += "5";
        invut.setText(number);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        number += "6";
        invut.setText(number);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        number += "7";
        invut.setText(number);
    }//GEN-LAST:event_num7ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        number += "0";
        invut.setText(number);
    }//GEN-LAST:event_num0ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        number += "9";
        invut.setText(number);
    }//GEN-LAST:event_num9ActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1 :nomor2= Double.parseDouble(String.valueOf(invut.getText())); 
                    jumlah = nomor1+nomor2;
                    invut.setText(Double.toString(jumlah));
                    break;
            case 2 :nomor2= Double.parseDouble(String.valueOf(invut.getText())); 
                    jumlah = nomor1-nomor2;
                    invut.setText(Double.toString(jumlah));
                    break;
            case 3 :nomor2= Double.parseDouble(String.valueOf(invut.getText())); 
                    jumlah = nomor1/nomor2;
                    invut.setText(Double.toString(jumlah));
                    break;
            case 4 :nomor2= Double.parseDouble(String.valueOf(invut.getText())); 
                    jumlah = nomor1*nomor2;
                    invut.setText(Double.toString(jumlah));
                    break;
            case 5 :nomor2= Double.parseDouble(String.valueOf(invut.getText())); 
                    jumlah = nomor1%nomor2;
                    invut.setText(Double.toString(jumlah));
                    break;
            case 6 :nomor2= Double.parseDouble(String.valueOf(invut.getText())); 
                    jumlah = Math.pow(nomor1,nomor2);
                    invut.setText(Double.toString(jumlah));
                    break;
            case 7 : 
                    jumlah = Math.tan(nomor1);
                    invut.setText(Double.toString(jumlah));
                    break;
            case 8 :
                    jumlah = Math.cos(nomor1);
                    invut.setText(Double.toString(jumlah));
                    break;
            case 9 :
                    jumlah = Math.sin(nomor1);
                    invut.setText(Double.toString(jumlah));
        }
    }//GEN-LAST:event_samadenganActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:

        invut.setText("");
        nomor1=0;
        nomor2=0;
        number="";
    }//GEN-LAST:event_hapusActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        number += "8";
        invut.setText(number);
    }//GEN-LAST:event_num8ActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("sin");
        pilih = 9;
    }//GEN-LAST:event_sinActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        
        invut.setText("+");
        number="";
        pilih = 1;
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("-");
        pilih = 2;
    }//GEN-LAST:event_minusActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("/");
        pilih = 3;
    }//GEN-LAST:event_bagiActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("x");
        pilih = 4;
    }//GEN-LAST:event_kaliActionPerformed

    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("Modulus");
        pilih = 5;
    }//GEN-LAST:event_modulusActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("pangkat");
        pilih = 6;
    }//GEN-LAST:event_pangkatActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        // TODO add your handling code here:
        nomor1 = Double.parseDouble(number);
        number="";
        invut.setText("cos");
        pilih = 8;
    }//GEN-LAST:event_cosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cos;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField invut;
    private javax.swing.JButton kali;
    private javax.swing.JButton minus;
    private javax.swing.JButton modulus;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton plus;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton sin;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables
}
